//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_EDITOR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DB_EDITOR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///930,3,9,0,4,5,4
        ///750,4,8,0,4,5,4
        ///1200,7,10,0,4,5,4
        ///930,6,2,0,4,5,4
        ///1080,5,1,0,4,5,4
        ///930,6,3,0,5,5,5
        ///750,4,10,0,5,5,5
        ///930,9,7,0,5,5,5
        ///1200,1,8,0,5,5,5
        ///1080,2,5,0,5,5,5
        ///930,4,6,0,6,5,6
        ///1200,9,5,0,6,5,6
        ///1080,10,2,0,6,5,6
        ///750,3,2,0,7,5,7
        ///1200,5,4,0,7,5,7
        ///1200,8,9,0,7,5,7
        ///930,6,7,0,7,5,7
        ///1080,1,10,0,7,5,7
        ///1080,10,3,0,8,5,8
        ///750,9,1,0,8,5,8
        ///1080,7,5,0,8,5,8
        ///1200,8,6,0,8,5,8
        ///930,3,5,0,9,5,9
        ///1200,4,9,0,9,5,9
        ///1080,2,7,0,9,4,9
        ///750,10,8,0,9,4,9
        ///1200,1,6,0,9,5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10_team {
            get {
                return ResourceManager.GetString("_10_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///1200,3,11,0,4,5,4
        ///750,9,1,0,4,5,4
        ///1080,2,8,0,4,5,4
        ///1080,6,7,0,4,5,4
        ///750,4,10,0,4,5,4
        ///750,11,9,0,5,5,5
        ///1080,5,8,0,5,5,5
        ///750,2,3,0,5,5,5
        ///750,7,4,0,5,5,5
        ///1080,11,5,0,6,5,6
        ///1200,9,6,0,6,5,6
        ///930,7,2,0,6,5,6
        ///1080,8,10,0,6,5,6
        ///1080,1,4,0,6,5,6
        ///750,5,9,0,7,5,7
        ///1200,4,2,0,7,5,7
        ///1080,3,1,0,7,5,7
        ///1080,8,7,0,7,5,7
        ///750,10,6,0,7,5,7
        ///930,4,11,0,8,5,8
        ///930,1,5,0,8,5,8
        ///930,2,9,0,8,5,8
        ///750,10,3,0,8,5,8
        ///1080,6,8,0,8,5,8
        ///930,8,11,0,9,5,9
        ///1080,5,3,0,9,5,9
        ///1200,2,10,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11_team {
            get {
                return ResourceManager.GetString("_11_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,Away,Home,SESI,SEWN,GDAT,SEWT
        ///1140,10,1,0,1,5,1
        ///930,12,3,0,1,5,1
        ///1185,5,8,0,1,5,1
        ///720,2,11,0,2,5,2
        ///1080,7,4,0,2,5,2
        ///720,9,6,0,2,5,2
        ///1200,1,4,0,3,5,3
        ///930,2,5,0,3,5,3
        ///750,3,6,0,3,4,3
        ///720,7,10,0,3,5,3
        ///930,8,11,0,3,5,3
        ///750,9,12,0,3,5,3
        ///1170,7,1,0,4,5,4
        ///1185,8,2,0,4,4,4
        ///720,9,3,0,4,5,4
        ///720,10,4,0,4,5,4
        ///930,11,5,0,4,4,4
        ///930,12,6,0,4,5,4
        ///930,5,1,0,5,5,5
        ///1080,4,3,0,5,5,5
        ///930,12,8,0,5,5,5
        ///930,6,2,0,6,5,6
        ///1200,11,7,0,6,5,6
        ///930,10,9,0,6,5,6
        ///1140,1,8,0,7,5,7
        ///930,3,7,0,7,5,7
        ///1140,5,12,0,7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12_team {
            get {
                return ResourceManager.GetString("_12_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///1200,1,3,0,1,5,1
        ///930,9,11,0,1,5,1
        ///750,6,8,0,1,5,1
        ///720,5,7,0,2,5,2
        ///930,2,4,0,2,5,2
        ///750,10,12,0,2,5,2
        ///1170,3,5,0,3,5,3
        ///1185,7,9,0,3,5,3
        ///720,11,13,0,3,5,3
        ///720,4,6,0,3,5,3
        ///930,8,10,0,3,5,3
        ///930,12,14,0,3,5,3
        ///930,2,3,0,4,4,4
        ///750,4,5,0,4,5,4
        ///930,6,7,0,4,5,4
        ///930,8,9,0,4,5,4
        ///1140,10,11,0,4,5,4
        ///1200,12,13,0,4,5,4
        ///1140,14,1,0,4,5,4
        ///1200,9,1,0,5,5,5
        ///930,11,3,0,5,4,5
        ///1170,6,14,0,5,5,5
        ///750,5,13,0,6,5,6
        ///930,10,2,0,6,4,6
        ///1200,12,4,0,6,5,6
        ///1200,13,1,0,7,5,7
        ///720,7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _14_team {
            get {
                return ResourceManager.GetString("_14_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///930,1,9,0,2,5,2
        ///930,3,11,0,2,5,2
        ///1080,5,13,0,2,5,2
        ///930,7,15,0,2,4,2
        ///1200,2,10,0,3,5,3
        ///1200,4,12,0,3,4,3
        ///1200,6,14,0,3,5,3
        ///750,8,16,0,3,5,3
        ///1200,13,1,0,4,5,4
        ///1080,14,2,0,4,5,4
        ///1200,15,3,0,4,5,4
        ///1200,16,4,0,4,5,4
        ///1200,9,5,0,4,4,4
        ///1080,10,6,0,4,5,4
        ///1080,11,7,0,4,5,4
        ///930,12,8,0,4,5,4
        ///1200,1,5,0,5,5,5
        ///1080,2,6,0,5,5,5
        ///1200,3,7,0,5,4,5
        ///750,4,8,0,5,5,5
        ///1200,9,13,0,5,5,5
        ///1080,10,14,0,5,5,5
        ///1080,11,15,0,5,5,5
        ///930,12,16,0,5,5,5
        ///930,10,1,0,6,5,6
        ///1080,9,2,0,6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _16_team {
            get {
                return ResourceManager.GetString("_16_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///930,1,7,0,3,5,3
        ///1200,3,9,0,3,5,3
        ///930,2,8,0,3,5,3
        ///930,5,11,0,3,4,3
        ///1200,4,10,0,3,5,3
        ///930,6,12,0,3,5,3
        ///1200,7,13,0,4,5,4
        ///1200,9,15,0,4,4,4
        ///1200,8,14,0,4,5,4
        ///1200,11,17,0,4,5,4
        ///750,10,16,0,4,5,4
        ///750,12,18,0,4,5,4
        ///1080,13,1,0,5,5,5
        ///930,15,3,0,5,4,5
        ///1080,14,2,0,5,4,5
        ///750,17,5,0,5,5,5
        ///1080,16,4,0,5,5,5
        ///1200,18,6,0,5,5,5
        ///750,7,3,0,6,5,6
        ///750,9,2,0,6,5,6
        ///1080,8,5,0,6,5,6
        ///1200,11,4,0,6,5,6
        ///1200,10,6,0,6,5,6
        ///930,12,1,0,6,5,6
        ///1200,13,15,0,6,5,6
        ///1080,14,17,0,6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _18_team {
            get {
                return ResourceManager.GetString("_18_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///750,2,1,0,2,5,2
        ///750,4,5,0,4,5,4
        ///1080,7,3,0,4,5,4
        ///930,6,2,0,5,5,5
        ///1080,5,7,0,5,5,5
        ///750,4,6,0,6,5,6
        ///1200,5,2,0,6,5,6
        ///1080,3,8,0,6,5,6
        ///930,8,5,0,7,5,7
        ///750,6,7,0,7,4,7
        ///750,2,4,0,7,5,7
        ///1080,1,3,0,7,5,7
        ///930,8,1,0,8,5,8
        ///1200,3,5,0,8,5,8
        ///1080,7,2,0,9,5,9
        ///930,6,8,0,9,5,9
        ///1200,1,4,0,9,5,9
        ///750,8,2,0,10,5,10
        ///1080,3,6,0,10,5,10
        ///1200,5,1,0,10,4,10
        ///930,4,7,0,10,4,10
        ///1080,2,3,0,11,5,11
        ///1200,7,1,0,11,5,11
        ///930,4,8,0,11,5,11
        ///1080,6,5,0,11,5,11
        ///1200,8,7,0,12,5,12
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8_team {
            get {
                return ResourceManager.GetString("_8_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///750,8,2,1,3,5,3
        ///930,3,1,1,3,5,3
        ///1200,4,2,1,4,5,4
        ///750,6,3,1,4,5,4
        ///1080,9,7,1,4,5,4
        ///1080,1,5,1,4,5,4
        ///750,5,3,1,5,5,5
        ///1200,4,8,1,5,4,5
        ///1080,7,6,1,5,5,5
        ///930,9,1,1,5,5,5
        ///1080,3,4,1,6,5,6
        ///1200,2,7,1,6,5,6
        ///750,9,5,1,6,4,6
        ///930,8,6,1,6,5,6
        ///1080,2,1,1,7,5,7
        ///1080,4,9,1,7,5,7
        ///1200,7,8,1,7,4,7
        ///930,6,5,1,7,5,7
        ///1200,3,2,1,8,5,8
        ///930,5,4,1,8,5,8
        ///1080,6,1,1,8,5,8
        ///930,2,6,1,9,5,9
        ///1080,7,3,1,9,5,9
        ///1200,1,4,1,9,5,9
        ///1200,8,9,1,9,5,9
        ///1080,9,3,1,10,5,10
        ///1200,4,6,1,10,5, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9_team {
            get {
                return ResourceManager.GetString("_9_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI,PFSH,PMSH,PSSH
        ///0.00,0,-1,4
        ///0.01,0,0,5
        ///0.02,0,0,5
        ///0.03,0,-1,4
        ///0.04,-1,-1,4
        ///0.05,-1,-1,4
        ///0.06,-1,0,3
        ///0.07,-1,-1,4
        ///0.08,-1,0,4
        ///0.09,-1,0,3
        ///0.10,0,-1,4
        ///0.11,-1,-1,4
        ///0.12,-1,-1,4
        ///0.13,-1,-1,4
        ///0.14,-1,-1,4
        ///0.15,-1,0,4
        ///0.16,-1,-1,4
        ///0.17,-1,-1,4
        ///0.18,-1,-1,4
        ///0.19,-1,-1,4
        ///0.20,-1,-1,4
        ///0.21,-1,-1,4
        ///0.22,0,-1,4
        ///0.23,-1,-1,4
        ///0.24,-1,-1,4
        ///0.25,-1,-1,4
        ///0.26,-1,-1,4
        ///0.27,-1,-1,4
        ///0.28,-1,-1,4
        ///0.29,-1,0,4
        ///0.30,-1,-1,4
        ///0.31,-1,-1,4
        ///0.32,-1,-1,4
        ///0.33,-1,0,4
        ///0.34,-1,-1,4
        ///0.35,-1,-1,4
        ///0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BMI_Calc {
            get {
                return ResourceManager.GetString("BMI_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGID,CFB-USA,TDNA
        ///1,Air Force Falcons,Air Force
        ///2,Akron Zips,Akron
        ///3,Alabama Crimson Tide,Alabama
        ///4,Arizona Wildcats,Arizona
        ///5,Arizona State Sun Devils,Arizona State
        ///6,Arkansas Razorbacks,Arkansas
        ///7,Arkansas State Indians,Arkansas State
        ///8,USMA Black Knights,Army
        ///9,Auburn Tigers,Auburn
        ///10,Ball State Cardinals,Ball State
        ///11,Baylor Bears,Baylor
        ///12,Boise State Broncos,Boise State
        ///13,Boston College Eagles,Boston College
        ///14,Bowling Green Falcons,Bowling Green
        ///15,Brigham Young Cougars,BYU
        ///16,Califo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string college_football_usa {
            get {
                return ResourceManager.GetString("college_football_usa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDNA,TGID,TMCP,TCRP
        ///Air Force,1,0,0
        ///Akron,2,1,1
        ///Alabama,3,2,3
        ///Alabama A&amp;M,116,115,2
        ///Alabama State,117,116,5
        ///Alcorn State,118,117,4
        ///Appalachian State,188,155,159
        ///Arizona,4,3,6
        ///Arizona State,5,4,12
        ///Ark - Pine Bluff,119,118,8
        ///Arkansas,6,5,7
        ///Arkansas State,7,6,9
        ///Army,8,7,10
        ///Auburn,9,8,11
        ///Ball State,10,9,13
        ///Baylor,11,10,14
        ///Bethune-Cookman,120,119,15
        ///Boise State,12,11,16
        ///Boston College,13,12,17
        ///Bowling Green,14,13,18
        ///Brown,121,120,19
        ///Buffalo,15,14,20
        ///BYU,16,15,21
        ///Cal,17,16,22
        ///Central Mich [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Color_Palettes {
            get {
                return ResourceManager.GetString("Color_Palettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap def_file {
            get {
                object obj = ResourceManager.GetObject("def file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGID,TEAM,PRESTIGE,League
        ///1,Air Force,2,0
        ///3,Alabama,6,0
        ///188,Appalachian State,3,0
        ///4,Arizona,4,0
        ///5,Arizona State,3,0
        ///6,Arkansas,4,0
        ///7,Arkansas State,2,0
        ///8,Army,2,0
        ///9,Auburn,4,0
        ///11,Baylor,4,0
        ///12,Boise State,3,0
        ///13,Boston College,3,0
        ///16,BYU,4,0
        ///17,Cal,3,0
        ///183,Charlotte,2,0
        ///20,Cincinnati,4,0
        ///21,Clemson,5,0
        ///178,Coastal Carolina,3,0
        ///22,Colorado,4,0
        ///23,Colorado State,2,0
        ///24,Duke,3,0
        ///25,ECU,3,0
        ///230,FIU,2,0
        ///27,Florida,4,0
        ///229,Florida Atlantic,2,0
        ///28,Florida State,5,0
        ///29,Fresno State,3,0
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FantasyGenData {
            get {
                return ResourceManager.GetString("FantasyGenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ncaa_db_editor_icon1 {
            get {
                object obj = ResourceManager.GetObject("ncaa_db_editor_icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ncaa_db_editor_TITLE {
            get {
                object obj = ResourceManager.GetObject("ncaa_db_editor_TITLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open2 {
            get {
                object obj = ResourceManager.GetObject("open2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPOS,PPST,MIN,MAX
        ///0,QB,0,9
        ///1,HB,20,29
        ///2,FB,40,49
        ///3,WR,80,89
        ///4,TE,40,49
        ///5,LT,60,79
        ///6,LG,60,79
        ///7,C,60,79
        ///8,RG,60,79
        ///9,RT,60,79
        ///10,LE,90,99
        ///11,RE,90,99
        ///12,DT,90,99
        ///13,LOLB,40,59
        ///14,MLB,40,59
        ///15,ROLB,40,59
        ///16,CB,10,19
        ///17,FS,30,39
        ///18,SS,30,39
        ///19,K,0,9
        ///20,P,0,9
        ///.
        /// </summary>
        internal static string PJEN {
            get {
                return ResourceManager.GetString("PJEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Air Force
        ///1,Akron
        ///2,Alabama
        ///3,Arizona State
        ///4,Arizona
        ///5,Arkansas
        ///6,Arkansas State
        ///7,Army
        ///8,Auburn
        ///9,BYU
        ///10,Ball State
        ///11,Baylor
        ///12,Boise State
        ///13,Boston College
        ///14,Bowling Green
        ///15,Buffalo
        ///16,Cal
        ///17,Central Michigan
        ///18,Cincinnati
        ///19,Clemson
        ///20,Colorado State
        ///21,Colorado
        ///22,Duke
        ///23,ECU
        ///24,Eastern Michigan
        ///25,Florida Atlantic
        ///26,FIU
        ///27,Florida State
        ///28,Florida
        ///29,Fresno State
        ///30,Georgia Tech
        ///31,Georgia
        ///32,Hawaii
        ///33,Houston
        ///34,Idaho
        ///35,Illinois
        ///36,Indiana
        ///37,Iowa State
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlaybookNames {
            get {
                return ResourceManager.GetString("PlaybookNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLDH,PLDL,PPOS,CAWT,KAWT,TAWT,PBWT,RBWT,ACWT,AGWT,TKWT,INWT,KPWT,SPWT,TPWT,BTWT,CTWT,STWT,JUWT,AWWT
        ///92,35,0,0,0,30,0,0,6,6,0,0,0,14,26,0,0,0,0,20
        ///93,35,1,10,0,0,2,0,18,18,0,0,0,25,0,15,5,2,0,5
        ///80,35,2,2,0,0,1,8,2,1,0,0,0,2,0,2,6,2,0,3
        ///96,35,3,0,0,0,0,0,10,10,0,0,0,25,0,5,30,0,5,5
        ///85,35,4,0,0,0,1,3,2,2,0,0,0,4,0,1,5,3,0,3
        ///95,35,5,0,0,0,6,5,1,1,0,0,0,1,0,0,0,4,0,4
        ///91,35,6,0,0,0,4,6,2,1,0,0,0,2,0,0,0,4,0,4
        ///91,35,7,0,0,0,4,6,2,1,0,0,0,2,0,0,0,4,0,4
        ///91,35,8,0,0,0,4,6,2,1,0,0,0,2,0,0,0,4,0,4
        ///95,35,9,0,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string POCI {
            get {
                return ResourceManager.GetString("POCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuiasosopo
        ///Tuivaiti
        ///Finau
        ///Tuigamala
        ///Tuipulotu
        ///Lauti
        ///Maafu
        ///Tuisamoa
        ///Matagi
        ///Togia
        ///Malieitulua
        ///Tuakoi
        ///Tupou
        ///Vaenuku
        ///Taumalolo
        ///Vaihola
        ///Fonoti
        ///Tuita
        ///Pulu
        ///Vaovasa
        ///Siaki
        ///Tavita
        ///Moeaki
        ///Hafoka
        ///Taukolo
        ///Maka
        ///Unga
        ///Taula
        ///Tavake
        ///Vakameilalo
        ///Uasike
        ///Savelio
        ///Teo
        ///Lavaka
        ///Katoa
        ///Niumatai
        ///Kauvaka
        ///Halangahu
        ///Tuipala
        ///Fonua
        ///Taufa
        ///Taulapapa
        ///Uasi
        ///Ngalu
        ///Kaufusi
        ///Taniela
        ///Vakapuna
        ///Veikoso
        ///Unger
        ///Kefu
        ///Taua
        ///Palepoi
        ///Tamaivena
        ///Tofa
        ///Fisiiahi
        ///Oloapu
        ///Vakauta
        ///Saumaki
        ///Likiliki
        ///Tuitavake
        ///Ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poly_surnames {
            get {
                return ResourceManager.GetString("poly_surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,PTHA
        ///1,PSTA
        ///2,PLEB
        ///3,PREB
        ///4,PKAC
        ///5,PACC
        ///6,PHED
        ///7,PSPD
        ///8,PPOE
        ///9,PBRE
        ///10,PEYE
        ///11,PFSH
        ///12,PLSH
        ///13,PMSH
        ///14,PRSH
        ///15,PSSH
        ///17,PCTH
        ///18,PAGI
        ///19,PSKI
        ///20,PINJ
        ///21,PTAK
        ///22,PPBK
        ///23,PRBK
        ///24,PNEK
        ///25,PFMK
        ///26,PBTK
        ///27,PHCL
        ///29,HELM
        ///30,PHAN
        ///31,PLHN
        ///32,PRHN
        ///33,PSLO
        ///34,PTTO
        ///35,PLFP
        ///36,PTHP
        ///37,PJMP
        ///38,PCAR
        ///39,PKPR
        ///40,PSTR
        ///41,PAWR
        ///43,PVIS
        ///44,PFJS
        ///45,PPOS
        ///46,PLWS
        ///47,PRWS
        ///49,PHGT
        ///50,PWGT
        ///51,PSLT
        ///.
        /// </summary>
        internal static string RCAT_MAPPER {
            get {
                return ResourceManager.GetString("RCAT_MAPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPSL,SPFN
        ///0,Vince
        ///1,Kenny
        ///2,Noah
        ///3,Emmanuel
        ///4,Isaac
        ///5,James
        ///6,Kyle
        ///7,Tre
        ///8,Christophe
        ///9,Luke
        ///10,Ryan
        ///11,Johnathan
        ///12,Benjamin
        ///13,David
        ///14,Camby
        ///15,Caleb
        ///16,Trey
        ///17,John Lee
        ///18,Jacob
        ///19,Matthew
        ///20,Elijah
        ///21,Jayden
        ///22,Ayden
        ///23,Everett
        ///24,Jorden
        ///25,Brandon
        ///26,Troy
        ///27,Alec
        ///28,Hawk
        ///29,Brad
        ///30,Corvan
        ///31,Michael
        ///32,Eian
        ///33,Haaziq
        ///34,Omar
        ///35,Nasir
        ///36,Micah
        ///37,Dane
        ///38,Thor
        ///39,McKenly
        ///40,Zachary
        ///41,Warren
        ///42,Kaleb
        ///43,Jensen
        ///44,Nate
        ///45,Mason
        ///46,Kalawaia
        ///47,Dalton
        ///48,Bra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RCFN {
            get {
                return ResourceManager.GetString("RCFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPSL,SPLN
        ///0,Sanford
        ///1,Ngaima
        ///2,Bush
        ///4,Michel
        ///5,Cochran
        ///6,Jones
        ///7,Patterson
        ///8,Bugg
        ///9,Herrera
        ///10,Hallstrom
        ///11,Booth
        ///12,Youngblood
        ///13,Mercer
        ///14,Eure
        ///15,Goff
        ///16,Humphrey
        ///17,Taylor
        ///18,Eldridge
        ///19,Trach
        ///20,Malloy
        ///21,Brockman
        ///22,Thiergood
        ///23,McCollough
        ///24,Smalley
        ///25,Gidrey
        ///26,Lewis
        ///27,Blackmon
        ///28,Mock
        ///29,Wimmer
        ///30,Roberts
        ///31,Taylor
        ///32,Mack
        ///33,Castonguay
        ///34,Daniels
        ///35,Fattah
        ///36,Rashid
        ///37,Davis
        ///38,Kinamon
        ///39,Paglialong
        ///40,O&apos;Neal
        ///41,Larrier
        ///42,Bryan
        ///43,Holcomb
        ///44,Jones
        ///45, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RCLN {
            get {
                return ResourceManager.GetString("RCLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAB,STID,STNM,SPDN,STMP,SPUP,STOR,RPCT,SPLT,SPRT
        ///AL,0,Alabama,8,89,41,0,15,23,9
        ///AK,1,Alaska,1,5,4,1,1,1,10
        ///AZ,2,Arizona,1,35,43,2,6,27,30
        ///AR,3,Arkansas,17,23,24,3,4,35,41
        ///CA,4,California,1,244,36,4,43,1,27
        ///CO,5,Colorado,30,22,49,5,4,43,15
        ///CT,6,Connecticut,29,11,20,6,2,31,38
        ///DE,7,Delaware,45,5,29,7,1,19,29
        ///FL,8,Florida,8,352,9,9,61,0,8
        ///GA,9,Georgia,8,195,41,10,34,0,39
        ///HI,10,Hawaii,10,21,42,11,4,1,42
        ///ID,11,Idaho,43,6,50,12,1,36,25
        ///IL,12,Illinois,16,69,48,13,12,24,13
        ///IN,13,Indiana,16,38,21,14,7, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RCST {
            get {
                return ResourceManager.GetString("RCST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name,Last Name,PPOS,TGID,Height,,Weight
        ///Jeremiah,Smith,3,70,75,75,55
        ///Ellis,Robinson,16,30,72,72,20
        ///Jaylen,Mbakwe,16,3,72,72,15
        ///Ryan,Williams,3,3,73,73,10
        ///Cameron,Coleman,3,9,76,76,25
        ///Justin,Williams,14,30,74,74,45
        ///D.J.,Lagway,0,27,75,75,65
        ///Julian,Sayin,0,70,74,74,30
        ///L.J.,McCray,10,27,79,79,105
        ///Dylan,Raiola,0,58,75,75,60
        ///Kobe,Black,16,92,73,73,30
        ///K.J.,Bolden,18,30,73,73,30
        ///Dominick,McKinley,12,45,77,77,130
        ///Terry,Bussey,3,93,71,71,25
        ///Williams,Nwaneri,11,56,79,79,100
        ///Micah,Hudson,3,94,73, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recruits {
            get {
                return ResourceManager.GetString("recruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save3 {
            get {
                object obj = ResourceManager.GetObject("save3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Air Force,Falcons
        ///2,Akron,Zips
        ///3,Alabama,Crimson Tide
        ///4,Arizona,Wildcats
        ///5,Arizona State,Sun Devils
        ///6,Arkansas,Razorbacks
        ///7,Arkansas State,Red Wolves
        ///8,Army,Black Knights
        ///9,Auburn,Tigers
        ///10,Ball State,Cardinals
        ///11,Baylor,Bears
        ///12,Boise State,Broncos
        ///13,Boston College,Eagles
        ///14,Bowling Green,Falcons
        ///15,Buffalo,Bulls
        ///16,BYU,Cougars
        ///17,Cal,Golden Bears
        ///18,UCF,Golden Knights
        ///19,Central Michigan,Chippewas
        ///20,Cincinnati,Bearcats
        ///21,Clemson,Tigers
        ///22,Colorado,Buffaloes
        ///23,Colorado State,Ram [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamDB {
            get {
                return ResourceManager.GetString("TeamDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben Finley,2,1255,0,0
        ///Marquese Williams,2,3845,0,1
        ///Israel Polk,2,5416,0,2
        ///Ahmarian Granger,2,11522,0,2
        ///Max Whisner,2,3976,0,3
        ///Dimitri Madden,2,7364,0,5
        ///Aman Greenwood,2,6163,0,7
        ///Elijah Reed,2,2971,0,7
        ///John McConnell,2,3257,0,9
        ///Austin Mack,3,7744,0,0
        ///Germie Bernard,3,7725,0,2
        ///Josh Cuevas,3,7763,0,3
        ///Geno VanDeMark,3,3701,0,4
        ///Parker Brailsford,3,7768,0,4
        ///Kadyn Proctor,3,219,0,4
        ///L.T. Overton,3,6518,0,5
        ///Domani Jackson,3,7151,0,7
        ///Keon Sabb,3,3605,0,7
        ///Dashawn Jones,3,7638,0,7
        ///King Mack,3,5382,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string transfers {
            get {
                return ResourceManager.GetString("transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName,LastName,Pos Group,TGID,
        ///Jordon,Simmons,1,2,Jordon Simmons
        ///Dayne,Shor,4,2,Dayne Shor
        ///Laurence,Seymoure,4,2,Laurence Seymoure
        ///Eli,Fields,4,2,Eli Fields
        ///Da&apos;Quan,Thomas,4,2,Da&apos;Quan Thomas
        ///Nathan,Kapongo,5,2,Nathan Kapongo
        ///Paul,Lewis,7,2,Paul Lewis
        ///Daymon,David,7,2,Daymon David
        ///Naquil,Betrand,4,3,Naquil Betrand
        ///Graham,Nicholson,8,3,Graham Nicholson
        ///Charles,Wright,0,188,Charles Wright
        ///William,Fowles,2,188,William Fowles
        ///Zavier,Short,2,188,Zavier Short
        ///Michael,Marotta,4,188,Michael Marotta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string transfers_gen {
            get {
                return ResourceManager.GetString("transfers_gen", resourceCulture);
            }
        }
    }
}
