//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_EDITOR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DB_EDITOR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///930,3,9,0,4,5,4
        ///750,4,8,0,4,5,4
        ///1200,7,10,0,4,5,4
        ///930,6,2,0,4,5,4
        ///1080,5,1,0,4,5,4
        ///930,6,3,0,5,5,5
        ///750,4,10,0,5,5,5
        ///930,9,7,0,5,5,5
        ///1200,1,8,0,5,5,5
        ///1080,2,5,0,5,5,5
        ///930,4,6,0,6,5,6
        ///1200,9,5,0,6,5,6
        ///1080,10,2,0,6,5,6
        ///750,3,2,0,7,5,7
        ///1200,5,4,0,7,5,7
        ///1200,8,9,0,7,5,7
        ///930,6,7,0,7,5,7
        ///1080,1,10,0,7,5,7
        ///1080,10,3,0,8,5,8
        ///750,9,1,0,8,5,8
        ///1080,7,5,0,8,5,8
        ///1200,8,6,0,8,5,8
        ///930,3,5,0,9,5,9
        ///1200,4,9,0,9,5,9
        ///1080,2,7,0,9,4,9
        ///750,10,8,0,9,4,9
        ///1200,1,6,0,9,5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10_team {
            get {
                return ResourceManager.GetString("_10_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///1200,3,11,0,4,5,4
        ///750,9,1,0,4,5,4
        ///1080,2,8,0,4,5,4
        ///1080,6,7,0,4,5,4
        ///750,4,10,0,4,5,4
        ///750,11,9,0,5,5,5
        ///1080,5,8,0,5,5,5
        ///750,2,3,0,5,5,5
        ///750,7,4,0,5,5,5
        ///1080,11,5,0,6,5,6
        ///1200,9,6,0,6,5,6
        ///930,7,2,0,6,5,6
        ///1080,8,10,0,6,5,6
        ///1080,1,4,0,6,5,6
        ///750,5,9,0,7,5,7
        ///1200,4,2,0,7,5,7
        ///1080,3,1,0,7,5,7
        ///1080,8,7,0,7,5,7
        ///750,10,6,0,7,5,7
        ///930,4,11,0,8,5,8
        ///930,1,5,0,8,5,8
        ///930,2,9,0,8,5,8
        ///750,10,3,0,8,5,8
        ///1080,6,8,0,8,5,8
        ///930,8,11,0,9,5,9
        ///1080,5,3,0,9,5,9
        ///1200,2,10,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11_team {
            get {
                return ResourceManager.GetString("_11_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,Away,Home,SESI,SEWN,GDAT,SEWT
        ///1140,10,1,0,1,5,1
        ///930,12,3,0,1,5,1
        ///1185,5,8,0,1,5,1
        ///720,2,11,0,2,5,2
        ///1080,7,4,0,2,5,2
        ///720,9,6,0,2,5,2
        ///1200,1,4,0,3,5,3
        ///930,2,5,0,3,5,3
        ///750,3,6,0,3,4,3
        ///720,7,10,0,3,5,3
        ///930,8,11,0,3,5,3
        ///750,9,12,0,3,5,3
        ///1170,7,1,0,4,5,4
        ///1185,8,2,0,4,4,4
        ///720,9,3,0,4,5,4
        ///720,10,4,0,4,5,4
        ///930,11,5,0,4,4,4
        ///930,12,6,0,4,5,4
        ///930,5,1,0,5,5,5
        ///1080,4,3,0,5,5,5
        ///930,12,8,0,5,5,5
        ///930,6,2,0,6,5,6
        ///1200,11,7,0,6,5,6
        ///930,10,9,0,6,5,6
        ///1140,1,8,0,7,5,7
        ///930,3,7,0,7,5,7
        ///1140,5,12,0,7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12_team {
            get {
                return ResourceManager.GetString("_12_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,Away,Home,SESI,SEWN,GDAT,SEWT
        ///1140,10,1,0,2,5,1
        ///930,12,3,0,2,5,1
        ///1185,5,8,0,2,5,1
        ///720,2,11,0,1,5,2
        ///1080,7,4,0,1,5,2
        ///720,9,6,0,1,5,2
        ///1200,1,4,0,4,5,3
        ///930,2,5,0,4,5,3
        ///750,3,6,0,4,4,3
        ///720,7,10,0,4,5,3
        ///930,8,11,0,4,5,3
        ///750,9,12,0,4,5,3
        ///1170,7,1,0,3,5,4
        ///1185,8,2,0,3,4,4
        ///720,9,3,0,3,5,4
        ///720,10,4,0,3,5,4
        ///930,11,5,0,3,4,4
        ///930,12,6,0,3,5,4
        ///930,5,1,0,5,5,5
        ///1080,4,3,0,6,5,5
        ///930,12,8,0,5,5,5
        ///930,6,2,0,6,5,6
        ///1200,11,7,0,5,5,6
        ///930,10,9,0,6,5,6
        ///1140,1,8,0,8,5,7
        ///930,3,7,0,7,5,7
        ///1140,5,12,0,8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12_teamB {
            get {
                return ResourceManager.GetString("_12_teamB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///1200,1,3,0,1,5,1
        ///930,9,11,0,1,5,1
        ///750,6,8,0,1,5,1
        ///720,5,7,0,2,5,2
        ///930,2,4,0,2,5,2
        ///750,10,12,0,2,5,2
        ///1170,3,5,0,3,5,3
        ///1185,7,9,0,3,5,3
        ///720,11,13,0,3,5,3
        ///720,4,6,0,3,5,3
        ///930,8,10,0,3,5,3
        ///930,12,14,0,3,5,3
        ///930,2,3,0,4,4,4
        ///750,4,5,0,4,5,4
        ///930,6,7,0,4,5,4
        ///930,8,9,0,4,5,4
        ///1140,10,11,0,4,5,4
        ///1200,12,13,0,4,5,4
        ///1140,14,1,0,4,5,4
        ///1200,9,1,0,5,5,5
        ///930,11,3,0,5,4,5
        ///1170,6,14,0,5,5,5
        ///750,5,13,0,6,5,6
        ///930,10,2,0,6,4,6
        ///1200,12,4,0,6,5,6
        ///1200,13,1,0,7,5,7
        ///720,7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _14_team {
            get {
                return ResourceManager.GetString("_14_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///930,1,9,0,2,5,2
        ///930,3,11,0,2,5,2
        ///1080,5,13,0,2,5,2
        ///930,7,15,0,2,4,2
        ///1200,2,10,0,3,5,3
        ///1200,4,12,0,3,4,3
        ///1200,6,14,0,3,5,3
        ///750,8,16,0,3,5,3
        ///1200,13,1,0,4,5,4
        ///1080,14,2,0,4,5,4
        ///1200,15,3,0,4,5,4
        ///1200,16,4,0,4,5,4
        ///1200,9,5,0,4,4,4
        ///1080,10,6,0,4,5,4
        ///1080,11,7,0,4,5,4
        ///930,12,8,0,4,5,4
        ///1200,1,5,0,5,5,5
        ///1080,2,6,0,5,5,5
        ///1200,3,7,0,5,4,5
        ///750,4,8,0,5,5,5
        ///1200,9,13,0,5,5,5
        ///1080,10,14,0,5,5,5
        ///1080,11,15,0,5,5,5
        ///930,12,16,0,5,5,5
        ///930,10,1,0,6,5,6
        ///1080,9,2,0,6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _16_team {
            get {
                return ResourceManager.GetString("_16_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///930,1,7,0,3,5,3
        ///1200,3,9,0,3,5,3
        ///930,2,8,0,3,5,3
        ///930,5,11,0,3,4,3
        ///1200,4,10,0,3,5,3
        ///930,6,12,0,3,5,3
        ///1200,7,13,0,4,5,4
        ///1200,9,15,0,4,4,4
        ///1200,8,14,0,4,5,4
        ///1200,11,17,0,4,5,4
        ///750,10,16,0,4,5,4
        ///750,12,18,0,4,5,4
        ///1080,13,1,0,5,5,5
        ///930,15,3,0,5,4,5
        ///1080,14,2,0,5,4,5
        ///750,17,5,0,5,5,5
        ///1080,16,4,0,5,5,5
        ///1200,18,6,0,5,5,5
        ///750,7,3,0,6,5,6
        ///750,9,2,0,6,5,6
        ///1080,8,5,0,6,5,6
        ///1200,11,4,0,6,5,6
        ///1200,10,6,0,6,5,6
        ///930,12,1,0,6,5,6
        ///1200,13,15,0,6,5,6
        ///1080,14,17,0,6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _18_team {
            get {
                return ResourceManager.GetString("_18_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///930,1,2,0,13,5,13
        ///1200,3,4,0,13,5,13
        ///930,5,1,0,11,5,11
        ///930,2,3,0,11,5,11
        ///1200,4,2,0,4,5,4
        ///930,5,3,0,4,5,4
        ///1200,3,1,0,6,5,6
        ///1200,4,5,0,6,5,6
        ///1200,1,4,0,15,5,15
        ///1200,2,5,0,15,5,15
        ///750,6,7,0,13,5,13
        ///750,8,9,0,13,5,13
        ///1080,10,6,0,11,5,11
        ///930,7,8,0,11,5,11
        ///1080,9,7,0,4,5,4
        ///750,10,8,0,4,5,4
        ///1080,8,6,0,6,5,6
        ///1200,9,10,0,6,5,6
        ///750,6,9,0,15,5,15
        ///750,7,10,0,15,5,15
        ///1080,11,12,0,13,4,13
        ///1200,13,14,0,13,5,13
        ///1200,15,11,0,11,5,11
        ///930,12,13,0,11,5,11
        ///1200,14,12, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _20_team {
            get {
                return ResourceManager.GetString("_20_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///750,2,1,0,2,5,2
        ///750,4,5,0,4,5,4
        ///1080,7,3,0,4,5,4
        ///930,6,2,0,5,5,5
        ///1080,5,7,0,5,5,5
        ///750,4,6,0,6,5,6
        ///1200,5,2,0,6,5,6
        ///1080,3,8,0,6,5,6
        ///930,8,5,0,7,5,7
        ///750,6,7,0,7,4,7
        ///750,2,4,0,7,5,7
        ///1080,1,3,0,7,5,7
        ///930,8,1,0,8,5,8
        ///1200,3,5,0,8,5,8
        ///1080,7,2,0,9,5,9
        ///930,6,8,0,9,5,9
        ///1200,1,4,0,9,5,9
        ///750,8,2,0,10,5,10
        ///1080,3,6,0,10,5,10
        ///1200,5,1,0,10,4,10
        ///930,4,7,0,10,4,10
        ///1080,2,3,0,11,5,11
        ///1200,7,1,0,11,5,11
        ///930,4,8,0,11,5,11
        ///1080,6,5,0,15,5,11
        ///1200,8,7,0,12,5,12
        ///10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8_team {
            get {
                return ResourceManager.GetString("_8_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTOD,GATG,GHTG,SESI,SEWN,GDAT,SEWT
        ///750,8,2,1,3,5,3
        ///930,3,1,1,3,5,3
        ///1200,4,2,1,4,5,4
        ///750,6,3,1,4,5,4
        ///1080,9,7,1,4,5,4
        ///1080,1,5,1,4,5,4
        ///750,5,3,1,5,5,5
        ///1200,4,8,1,5,4,5
        ///1080,7,6,1,5,5,5
        ///930,9,1,1,5,5,5
        ///1080,3,4,1,6,5,6
        ///1200,2,7,1,6,5,6
        ///750,9,5,1,6,4,6
        ///930,8,6,1,6,5,6
        ///1080,2,1,1,7,5,7
        ///1080,4,9,1,7,5,7
        ///1200,7,8,1,7,4,7
        ///930,6,5,1,7,5,7
        ///1200,3,2,1,8,5,8
        ///930,5,4,1,8,5,8
        ///1080,6,1,1,8,5,8
        ///930,2,6,1,9,5,9
        ///1080,7,3,1,9,5,9
        ///1200,1,4,1,9,5,9
        ///1200,8,9,1,9,5,9
        ///1080,9,3,1,10,5,10
        ///1200,4,6,1,10,5, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9_team {
            get {
                return ResourceManager.GetString("_9_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Goal,0,
        ///Short Yardage,1,
        ///Stop Clock,2,
        ///Goaline,3,
        ///Redzone,4,
        ///Inside Five,5,
        ///Normal,6,
        ///Medium Yardage,7,
        ///Long Yardage,8,
        ///Punt,9,
        ///Conserve Time,10,
        ///Fake Punt,11,
        ///Fake FG,12,
        ///Waste Time,13,
        ///QB Kneel,14,
        ///Normal Kickoff,15,
        ///Onside Kick,16,
        ///Run,17,
        ///Safety Kickoff,18,
        ///Max Protect Punt,19,
        ///Pass,20,
        ///Hail Mary,21,
        ///Extra Point,22,Goaline Pass
        ///Sky Punt,23,2nd &amp; Short
        ///2nd &amp; Medium,24,
        ///2nd &amp; Long,25,
        ///3rd &amp; short,26,
        ///3rd &amp; Medium,27,
        ///3rd &amp; Long,28,
        ///Unused,29,
        ///Unused,30,
        ///Unused,31,
        ///Spi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AIGR {
            get {
                return ResourceManager.GetString("AIGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal,0
        ///Trips Run,1
        ///Pass,2
        ///Kick Return,3
        ///Kick Return Onside,4
        ///Goaline Run,5
        ///Nickel Run,6
        ///Goaline Pass,7
        ///Kickoff Return Safety,8
        ///Punt Return Block,9
        ///Pass 3WR,10
        ///Trips Pass,11
        ///Trips,12
        ///Nickel Pass,13
        ///Punt Return Safe,15
        ///Field Goal Block,16
        ///Field Goal Safe,17
        ///Run,18
        ///Run 3WR,19
        ///Nickel,20
        ///Dime,21
        ///Goaline,22
        ///Hail Mary,23
        ///Dime Pass,24
        ///,25
        ///,26
        ///,27
        ///,28
        ///,29
        ///,30
        ///,31
        ///,32
        ///,33
        ///,34
        ///,35
        ///,36
        ///,37
        ///,38
        ///,39
        ///,40
        ///.
        /// </summary>
        internal static string AIGR_DEF {
            get {
                return ResourceManager.GetString("AIGR_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB,Attribute
        ///PACC,Acceleration
        ///PAGI,Agility
        ///PAWR,Awareness
        ///PCAR,Ball Carrying
        ///PBTK,Break Tackles
        ///PCTH,Catching
        ///PIMP,Importance
        ///PINJ,Injury
        ///PJMP,Jumping
        ///PKAC,Kick Accuracy
        ///PKPR,Kick Power
        ///PPBK,Pass Block
        ///PPOE,Potential
        ///PRBK,Run Block
        ///PSPD,Speed
        ///PSTA,Stamina
        ///PSTR,Strength
        ///PTAK,Tackling
        ///PTHA,Throw Accuracy
        ///PTHP,Throw Power
        ///.
        /// </summary>
        internal static string attributes {
            get {
                return ResourceManager.GetString("attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QB,HB,FB,WR,TE,RT,RG,C,LG,LT,RE,DT,LE,ROLB,MLB,LOLB,CB,FS,SS,K,P,PPOS
        ///0,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,2,0
        ///2,0,1,1,1,3,3,3,3,3,3,3,3,2,2,2,3,3,2,3,3,1
        ///1,0,0,2,1,3,3,3,3,3,3,3,3,1,1,1,3,3,3,3,3,2
        ///1,1,3,0,1,3,3,3,3,3,3,3,3,3,3,3,1,1,2,2,2,3
        ///2,2,1,1,0,2,3,3,3,2,3,3,3,2,2,2,3,3,2,3,3,4
        ///3,3,2,3,2,0,1,2,1,0,2,1,2,3,3,3,3,3,3,3,3,5
        ///3,3,2,3,2,1,0,1,0,1,2,1,2,3,3,3,3,3,3,3,3,6
        ///3,3,2,3,2,1,1,0,1,1,2,1,2,3,3,3,3,3,3,3,3,7
        ///3,3,2,3,2,1,0,1,0,1,2,1,2,3,3,3,3,3,3,3,3,8
        ///3,3,2,3,2,0,1,2,1,0,2,1,2,3,3,3,3,3, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Awareness {
            get {
                return ResourceManager.GetString("Awareness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI,PFSH,PMSH,PSSH
        ///0.00,0,-1,4
        ///0.01,0,0,5
        ///0.02,0,0,5
        ///0.03,0,-1,4
        ///0.04,-1,-1,4
        ///0.05,-1,-1,4
        ///0.06,-1,0,3
        ///0.07,-1,-1,4
        ///0.08,-1,0,4
        ///0.09,-1,0,3
        ///0.10,0,-1,4
        ///0.11,-1,-1,4
        ///0.12,-1,-1,4
        ///0.13,-1,-1,4
        ///0.14,-1,-1,4
        ///0.15,-1,0,4
        ///0.16,-1,-1,4
        ///0.17,-1,-1,4
        ///0.18,-1,-1,4
        ///0.19,-1,-1,4
        ///0.20,-1,-1,4
        ///0.21,-1,-1,4
        ///0.22,0,-1,4
        ///0.23,-1,-1,4
        ///0.24,-1,-1,4
        ///0.25,-1,-1,4
        ///0.26,-1,-1,4
        ///0.27,-1,-1,4
        ///0.28,-1,-1,4
        ///0.29,-1,0,4
        ///0.30,-1,-1,4
        ///0.31,-1,-1,4
        ///0.32,-1,-1,4
        ///0.33,-1,0,4
        ///0.34,-1,-1,4
        ///0.35,-1,-1,4
        ///0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BMI_Calc {
            get {
                return ResourceManager.GetString("BMI_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI,PFSH,PMSH,PSSH
        ///0.00,0,-1,4
        ///0.01,0,0,5
        ///0.02,0,0,5
        ///0.03,0,-1,4
        ///0.04,-1,-1,4
        ///0.05,-1,-1,4
        ///0.06,-1,0,3
        ///0.07,-1,-1,4
        ///0.08,-1,0,4
        ///0.09,-1,0,3
        ///0.10,0,-1,4
        ///0.11,-1,-1,4
        ///0.12,-1,-1,4
        ///0.13,-1,-1,4
        ///0.14,-1,-1,4
        ///0.15,-1,0,4
        ///0.16,-1,-1,4
        ///0.17,-1,-1,4
        ///0.18,-1,-1,4
        ///0.19,-1,-1,4
        ///0.20,-1,-1,4
        ///0.21,-1,-1,4
        ///0.22,0,-1,4
        ///0.23,-1,-1,4
        ///0.24,-1,-1,4
        ///0.25,-1,-1,4
        ///0.26,-1,-1,4
        ///0.27,-1,-1,4
        ///0.28,-1,-1,4
        ///0.29,-1,0,4
        ///0.30,-1,-1,4
        ///0.31,-1,-1,4
        ///0.32,-1,-1,4
        ///0.33,-1,0,4
        ///0.34,-1,-1,4
        ///0.35,-1,-1,4
        ///0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BMI_Calc1 {
            get {
                return ResourceManager.GetString("BMI_Calc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPOS,Height,Weight
        ///0,74,208
        ///1,71,205
        ///2,73,236
        ///3,73,192
        ///4,76,243
        ///5,76,301
        ///6,76,301
        ///7,76,297
        ///8,76,301
        ///9,76,301
        ///10,75,273
        ///11,75,298
        ///12,75,273
        ///13,74,227
        ///14,74,227
        ///15,74,227
        ///16,72,185
        ///17,72,191
        ///18,72,191
        ///19,73,197
        ///20,73,197
        ///.
        /// </summary>
        internal static string Body_Size_AVG {
            get {
                return ResourceManager.GetString("Body_Size_AVG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGID,CFB-USA,TDNA
        ///1,Air Force Falcons,Air Force
        ///2,Akron Zips,Akron
        ///3,Alabama Crimson Tide,Alabama
        ///4,Arizona Wildcats,Arizona
        ///5,Arizona State Sun Devils,Arizona State
        ///6,Arkansas Razorbacks,Arkansas
        ///7,Arkansas State Indians,Arkansas State
        ///8,USMA Black Knights,Army
        ///9,Auburn Tigers,Auburn
        ///10,Ball State Cardinals,Ball State
        ///11,Baylor Bears,Baylor
        ///12,Boise State Broncos,Boise State
        ///13,Boston College Eagles,Boston College
        ///14,Bowling Green Falcons,Bowling Green
        ///15,Brigham Young Cougars,BYU
        ///16,Califo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string college_football_usa {
            get {
                return ResourceManager.GetString("college_football_usa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDNA,TGID,TMCP,TCRP
        ///Air Force,1,0,0
        ///Akron,2,1,1
        ///Alabama,3,2,3
        ///Alabama A&amp;M,116,115,2
        ///Alabama State,117,116,5
        ///Alcorn State,118,117,4
        ///Appalachian State,188,155,159
        ///Arizona,4,3,6
        ///Arizona State,5,4,12
        ///Ark - Pine Bluff,119,118,8
        ///Arkansas,6,5,7
        ///Arkansas State,7,6,9
        ///Army,8,7,10
        ///Auburn,9,8,11
        ///Ball State,10,9,13
        ///Baylor,11,10,14
        ///Bethune-Cookman,120,119,15
        ///Boise State,12,11,16
        ///Boston College,13,12,17
        ///Bowling Green,14,13,18
        ///Brown,121,120,19
        ///Buffalo,15,14,20
        ///BYU,16,15,21
        ///Cal,17,16,22
        ///Central Mich [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Color_Palettes {
            get {
                return ResourceManager.GetString("Color_Palettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap def_file {
            get {
                object obj = ResourceManager.GetObject("def file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TGID,TEAM,PRESTIGE,League
        ///1,Air Force,2,0
        ///3,Alabama,6,0
        ///188,Appalachian State,3,0
        ///4,Arizona,4,0
        ///5,Arizona State,3,0
        ///6,Arkansas,4,0
        ///7,Arkansas State,2,0
        ///8,Army,2,0
        ///9,Auburn,4,0
        ///11,Baylor,4,0
        ///12,Boise State,3,0
        ///13,Boston College,3,0
        ///16,BYU,4,0
        ///17,Cal,3,0
        ///183,Charlotte,2,0
        ///20,Cincinnati,4,0
        ///21,Clemson,5,0
        ///178,Coastal Carolina,3,0
        ///22,Colorado,4,0
        ///23,Colorado State,2,0
        ///24,Duke,3,0
        ///25,ECU,3,0
        ///230,FIU,2,0
        ///27,Florida,4,0
        ///229,Florida Atlantic,2,0
        ///28,Florida State,5,0
        ///29,Fresno State,3,0
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FantasyGenData {
            get {
                return ResourceManager.GetString("FantasyGenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ncaa_db_editor_icon1 {
            get {
                object obj = ResourceManager.GetObject("ncaa_db_editor_icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ncaa_db_editor_TITLE {
            get {
                object obj = ResourceManager.GetObject("ncaa_db_editor_TITLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open2 {
            get {
                object obj = ResourceManager.GetObject("open2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPOS,PPST,MIN,MAX
        ///0,QB,0,9
        ///1,HB,20,29
        ///2,FB,40,49
        ///3,WR,80,89
        ///4,TE,40,49
        ///5,LT,60,79
        ///6,LG,60,79
        ///7,C,60,79
        ///8,RG,60,79
        ///9,RT,60,79
        ///10,LE,90,99
        ///11,RE,90,99
        ///12,DT,90,99
        ///13,LOLB,40,59
        ///14,MLB,40,59
        ///15,ROLB,40,59
        ///16,CB,10,19
        ///17,FS,30,39
        ///18,SS,30,39
        ///19,K,0,9
        ///20,P,0,9
        ///.
        /// </summary>
        internal static string PJEN {
            get {
                return ResourceManager.GetString("PJEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Air Force
        ///1,Akron
        ///2,Alabama
        ///3,Arizona State
        ///4,Arizona
        ///5,Arkansas
        ///6,Arkansas State
        ///7,Army
        ///8,Auburn
        ///9,BYU
        ///10,Ball State
        ///11,Baylor
        ///12,Boise State
        ///13,Boston College
        ///14,Bowling Green
        ///15,Buffalo
        ///16,Cal
        ///17,Central Michigan
        ///18,Cincinnati
        ///19,Clemson
        ///20,Colorado State
        ///21,Colorado
        ///22,Duke
        ///23,ECU
        ///24,Eastern Michigan
        ///25,Florida Atlantic
        ///26,FIU
        ///27,Florida State
        ///28,Florida
        ///29,Fresno State
        ///30,Georgia Tech
        ///31,Georgia
        ///32,Hawaii
        ///33,Houston
        ///34,Idaho
        ///35,Illinois
        ///36,Indiana
        ///37,Iowa State
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlaybookNames {
            get {
                return ResourceManager.GetString("PlaybookNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETL,PLYL,SITT,PLYT,PLF_,ord_,name,risk,motn,phlp,vpos
        ///2,2,2,36,97,21,Cover 3 Switch,0,0,7,3
        ///5,5,2,21,0,2,Kickoff Middle,0,1,7,0
        ///7,7,2,35,0,2,Return Middle,0,0,7,0
        ///8,8,2,21,0,2,Punt Middle,0,1,7,0
        ///5,9,2,21,0,1,Kickoff Left,0,1,7,0
        ///5,10,2,21,0,3,Kickoff Right,0,1,7,0
        ///2,12,2,39,21,32,Lightning Gold,0,1,7,4
        ///12,18,2,21,163840,7,Punt OB Left,0,1,7,0
        ///38,411,2,21,16384,11,Field Goal,0,0,7,1
        ///39,412,2,35,0,9,All Out Block,0,1,7,10
        ///40,413,2,33,0,11,FG Block,0,0,7,5
        ///12,452,2,3,32768,1,Spread Pass,0,0,7,0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PLYL {
            get {
                return ResourceManager.GetString("PLYL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETL,PLYL,SITT,PLYT,PLF_,ord_,name,risk,motn,phlp,vpos
        ///2,2,2,36,97,21,Cover 3 Switch,0,0,7,3
        ///2,12,2,39,21,32,Lightning Gold,0,1,7,4
        ///2,503,2,37,3,17,Hulk 3,0,1,7,7
        ///2,512,2,34,1073,22,Spy Gold,0,1,7,0
        ///2,513,2,39,21,7,Dog Gold,0,1,7,5
        ///2,514,2,39,25,10,Crash Gold,0,1,7,6
        ///2,515,2,38,1,31,Gold Double X,0,1,7,6
        ///2,516,2,38,1,16,Gold Double Y,0,1,7,5
        ///2,517,2,38,1,19,Gold Double Z,0,1,7,5
        ///2,519,2,38,27,11,Fire Green,0,1,7,6
        ///2,526,2,34,49,1,Cover 2 Man,0,1,7,0
        ///2,552,2,39,69,24,Dog 3,0,1,7,5
        ///2,556,2,37,11, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PLYL_Custom {
            get {
                return ResourceManager.GetString("PLYL_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETL,PLYL,SITT,PLYT,PLF_,ord_,name,risk,motn,phlp,vpos
        ///2,2,2,36,97,21,Cover 3 Switch,0,0,7,3
        ///2,12,2,39,21,32,Lightning Gold,0,1,7,4
        ///2,503,2,37,3,17,Hulk 3,0,1,7,7
        ///2,512,2,34,1073,22,Spy Gold,0,1,7,0
        ///2,513,2,39,21,7,Dog Gold,0,1,7,5
        ///2,514,2,39,25,10,Crash Gold,0,1,7,6
        ///2,515,2,38,1,31,Gold Double X,0,1,7,6
        ///2,516,2,38,1,16,Gold Double Y,0,1,7,5
        ///2,517,2,38,1,19,Gold Double Z,0,1,7,5
        ///2,519,2,38,27,11,Fire Green,0,1,7,6
        ///2,526,2,34,49,1,Cover 2 Man,0,1,7,0
        ///2,552,2,39,69,24,Dog 3,0,1,7,5
        ///2,556,2,37,11, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PLYL_NEXT25 {
            get {
                return ResourceManager.GetString("PLYL_NEXT25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLDH,PLDL,PPOS,CAWT,KAWT,TAWT,PBWT,RBWT,ACWT,AGWT,TKWT,INWT,KPWT,SPWT,TPWT,BTWT,CTWT,STWT,JUWT,AWWT
        ///92,35,0,0,0,30,0,0,6,6,0,0,0,14,26,0,0,0,0,20
        ///93,35,1,10,0,0,2,0,10,10,0,0,0,20,0,16,4,3,0,8
        ///79,35,2,2,0,0,3,8,2,1,0,0,0,2,0,3,5,2,0,4
        ///96,35,3,0,0,0,0,0,10,10,0,0,0,25,0,5,30,0,5,10
        ///85,35,4,0,0,0,1,3,2,2,0,0,0,4,0,1,5,3,0,3
        ///96,35,5,0,0,0,6,5,1,1,0,0,0,1,0,0,0,4,0,4
        ///91,35,6,0,0,0,4,6,2,1,0,0,0,2,0,0,0,4,0,4
        ///91,35,7,0,0,0,5,5,2,1,0,0,0,2,0,0,0,4,0,4
        ///91,35,8,0,0,0,4,6,2,1,0,0,0,2,0,0,0,4,0,4
        ///96,35,9,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string POCI_NEXT {
            get {
                return ResourceManager.GetString("POCI_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUVL,LURT
        ///0,40
        ///1,44
        ///2,48
        ///3,52
        ///4,56
        ///5,59
        ///6,62
        ///7,65
        ///8,68
        ///9,70
        ///10,72
        ///11,74
        ///12,76
        ///13,78
        ///14,80
        ///15,82
        ///16,84
        ///17,85
        ///18,86
        ///19,87
        ///20,88
        ///21,89
        ///22,90
        ///23,91
        ///24,92
        ///25,93
        ///26,94
        ///27,95
        ///28,96
        ///29,97
        ///30,98
        ///31,99
        ///.
        /// </summary>
        internal static string PRLU {
            get {
                return ResourceManager.GetString("PRLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPOS,TEN1,TEN2,TEN3
        ///0,Pocket Passer,Balanced,Scrambler
        ///1,Power,Balanced,Speed
        ///2,Blocking,Balanced,Receiving
        ///3,Speed,Balanced,Possession
        ///4,Blocking,Balanced,Receiving
        ///5,Run Blocker,Balanced,Pass Blocker
        ///6,Run Blocker,Balanced,Pass Blocker
        ///7,Run Blocker,Balanced,Pass Blocker
        ///8,Run Blocker,Balanced,Pass Blocker
        ///9,Run Blocker,Balanced,Pass Blocker
        ///10,Pass Rusher,Balanced,Run Stopper
        ///11,Pass Rusher,Balanced,Run Stopper
        ///12,Pass Rusher,Balanced,Run Stopper
        ///13,Run Stopper,Balanced,Coverage
        ///14,Run Sto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PTEN {
            get {
                return ResourceManager.GetString("PTEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,PTHA
        ///1,PSTA
        ///2,PLEB
        ///3,PREB
        ///4,PKAC
        ///5,PACC
        ///6,PHED
        ///7,PSPD
        ///8,PPOE
        ///9,PBRE
        ///10,PEYE
        ///11,PFSH
        ///12,PLSH
        ///13,PMSH
        ///14,PRSH
        ///15,PSSH
        ///17,PCTH
        ///18,PAGI
        ///19,PSKI
        ///20,PINJ
        ///21,PTAK
        ///22,PPBK
        ///23,PRBK
        ///24,PNEK
        ///25,PFMK
        ///26,PBTK
        ///27,PHCL
        ///29,HELM
        ///30,PHAN
        ///31,PLHN
        ///32,PRHN
        ///33,PSLO
        ///34,PTTO
        ///35,PLFP
        ///36,PTHP
        ///37,PJMP
        ///38,PCAR
        ///39,PKPR
        ///40,PSTR
        ///41,PAWR
        ///43,PVIS
        ///44,PFJS
        ///45,PPOS
        ///46,PLWS
        ///47,PRWS
        ///49,PHGT
        ///50,PWGT
        ///51,PSLT
        ///.
        /// </summary>
        internal static string RCAT_MAPPER {
            get {
                return ResourceManager.GetString("RCAT_MAPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTHA,PSTA,PLEB,PREB,PKAC,PACC,PHED,PSPD,PPOE,PBRE,PEYE,PFSH,PLSH,PMSH,PRSH,PSSH,RATH,PCTH,PAGI,PSKI,PINJ,PTAK,PPBK,PRBK,PNEK,PFMK,PBTK,PHCL,SPSL,HELM,PHAN,PLHN,PRHN,PSLO,PTTO,PLFP,PTHP,PJMP,PCAR,PKPR,PSTR,PAWR,PDIS,PVIS,PFJS,PPOS,PLWS,PRWS,MRCT,PHGT,PWGT,PSLT
        ///0,19,11,11,1,20,7,25,22,1,0,-1,0,-1,0,4,0,12,21,1,22,3,1,2,0,1,0,2,0,0,0,2,2,0,0,0,0,16,2,0,0,1,6,1,0,3,0,0,1,72,19,2
        ///0,20,11,11,0,17,2,13,26,1,0,1,0,3,0,3,0,3,12,4,18,13,0,2,0,4,0,0,1,0,0,2,2,0,0,0,0,9,2,0,10,7,2,1,0,13,6,6,1,76,70,2
        ///0,10,11,0,0,13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RCAT_NEXT {
            get {
                return ResourceManager.GetString("RCAT_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPFN
        ///Vince
        ///Kenny
        ///Noah
        ///Emmanuel
        ///Isaac
        ///James
        ///Kyle
        ///Tre
        ///Christophe
        ///Luke
        ///Ryan
        ///Johnathan
        ///Benjamin
        ///David
        ///Camby
        ///Caleb
        ///Trey
        ///John Lee
        ///Jacob
        ///Matthew
        ///Elijah
        ///Jayden
        ///Ayden
        ///Everett
        ///Jorden
        ///Brandon
        ///Troy
        ///Alec
        ///Hawk
        ///Brad
        ///Corvan
        ///Michael
        ///Eian
        ///Haaziq
        ///Omar
        ///Nasir
        ///Micah
        ///Dane
        ///Thor
        ///McKenly
        ///Zachary
        ///Warren
        ///Kaleb
        ///Jensen
        ///Nate
        ///Mason
        ///Kalawaia
        ///Dalton
        ///Brandon
        ///Demonte
        ///Deandre
        ///David
        ///Lakota
        ///Kolby
        ///Jordan
        ///Jalen
        ///Owen
        ///Wesley
        ///Ben
        ///Charles
        ///Jake
        ///Matthew
        ///Ben
        ///Caden
        ///Ethan
        ///Jayden
        ///Adam
        ///Mark        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RCFN {
            get {
                return ResourceManager.GetString("RCFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPLN
        ///Sanford
        ///Ngaima
        ///Bush
        ///Michel
        ///Cochran
        ///Jones
        ///Patterson
        ///Bugg
        ///Herrera
        ///Hallstrom
        ///Booth
        ///Youngblood
        ///Mercer
        ///Eure
        ///Goff
        ///Humphrey
        ///Taylor
        ///Eldridge
        ///Trach
        ///Malloy
        ///Brockman
        ///Thiergood
        ///McCollough
        ///Smalley
        ///Gidrey
        ///Lewis
        ///Blackmon
        ///Mock
        ///Wimmer
        ///Roberts
        ///Taylor
        ///Mack
        ///Castonguay
        ///Daniels
        ///Fattah
        ///Rashid
        ///Davis
        ///Kinamon
        ///Paglialong
        ///O&apos;Neal
        ///Larrier
        ///Bryan
        ///Holcomb
        ///Jones
        ///Polk
        ///Bugg
        ///Pescaia
        ///King
        ///Gooding
        ///Meeks
        ///Hughes
        ///Cormier
        ///Wills
        ///Barker
        ///Jackson
        ///Mergerson
        ///Burk
        ///Ndago
        ///Brittain
        ///Bein
        ///Spiewak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RCLN {
            get {
                return ResourceManager.GetString("RCLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name,Last Name,PPOS,TGID,Height,,Weight
        ///Jeremiah,Smith,3,70,75,75,55
        ///Ellis,Robinson,16,30,72,72,20
        ///Jaylen,Mbakwe,16,3,72,72,15
        ///Ryan,Williams,3,3,73,73,10
        ///Cameron,Coleman,3,9,76,76,25
        ///Justin,Williams,14,30,74,74,45
        ///D.J.,Lagway,0,27,75,75,65
        ///Julian,Sayin,0,70,74,74,30
        ///L.J.,McCray,10,27,79,79,105
        ///Dylan,Raiola,0,58,75,75,60
        ///Kobe,Black,16,92,73,73,30
        ///K.J.,Bolden,18,30,73,73,30
        ///Dominick,McKinley,12,45,77,77,130
        ///Terry,Bussey,3,93,71,71,25
        ///Williams,Nwaneri,11,56,79,79,100
        ///Micah,Hudson,3,94,73, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recruits {
            get {
                return ResourceManager.GetString("recruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save3 {
            get {
                object obj = ResourceManager.GetObject("save3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Air Force,Falcons
        ///2,Akron,Zips
        ///3,Alabama,Crimson Tide
        ///4,Arizona,Wildcats
        ///5,Arizona State,Sun Devils
        ///6,Arkansas,Razorbacks
        ///7,Arkansas State,Red Wolves
        ///8,Army,Black Knights
        ///9,Auburn,Tigers
        ///10,Ball State,Cardinals
        ///11,Baylor,Bears
        ///12,Boise State,Broncos
        ///13,Boston College,Eagles
        ///14,Bowling Green,Falcons
        ///15,Buffalo,Bulls
        ///16,BYU,Cougars
        ///17,Cal,Golden Bears
        ///18,UCF,Golden Knights
        ///19,Central Michigan,Chippewas
        ///20,Cincinnati,Bearcats
        ///21,Clemson,Tigers
        ///22,Colorado,Buffaloes
        ///23,Colorado State,Ram [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TeamDB {
            get {
                return ResourceManager.GetString("TeamDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ben Finley,2,1255,0,0
        ///Marquese Williams,2,3845,0,1
        ///Israel Polk,2,5416,0,2
        ///Ahmarian Granger,2,11522,0,2
        ///Max Whisner,2,3976,0,3
        ///Dimitri Madden,2,7364,0,5
        ///Aman Greenwood,2,6163,0,7
        ///Elijah Reed,2,2971,0,7
        ///John McConnell,2,3257,0,9
        ///Austin Mack,3,7744,0,0
        ///Germie Bernard,3,7725,0,2
        ///Josh Cuevas,3,7763,0,3
        ///Geno VanDeMark,3,3701,0,4
        ///Parker Brailsford,3,7768,0,4
        ///Kadyn Proctor,3,219,0,4
        ///L.T. Overton,3,6518,0,5
        ///Domani Jackson,3,7151,0,7
        ///Keon Sabb,3,3605,0,7
        ///Dashawn Jones,3,7638,0,7
        ///King Mack,3,5382,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string transfers {
            get {
                return ResourceManager.GetString("transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName,LastName,Pos Group,TGID,
        ///Jordon,Simmons,1,2,Jordon Simmons
        ///Dayne,Shor,4,2,Dayne Shor
        ///Laurence,Seymoure,4,2,Laurence Seymoure
        ///Eli,Fields,4,2,Eli Fields
        ///Da&apos;Quan,Thomas,4,2,Da&apos;Quan Thomas
        ///Nathan,Kapongo,5,2,Nathan Kapongo
        ///Paul,Lewis,7,2,Paul Lewis
        ///Daymon,David,7,2,Daymon David
        ///Naquil,Betrand,4,3,Naquil Betrand
        ///Graham,Nicholson,8,3,Graham Nicholson
        ///Charles,Wright,0,188,Charles Wright
        ///William,Fowles,2,188,William Fowles
        ///Zavier,Short,2,188,Zavier Short
        ///Michael,Marotta,4,188,Michael Marotta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string transfers_gen {
            get {
                return ResourceManager.GetString("transfers_gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name,UFID,TOID,TUCO
        ///Air Force,0,1,1
        ///Air Force,1,1,0
        ///Air Force,2,1,2
        ///Air Force,3,1,3
        ///Akron,4,2,1
        ///Akron,5,2,0
        ///Alabama,8,3,1
        ///Alabama,9,3,0
        ///Alabama A&amp;M,6,116,1
        ///Alabama A&amp;M,7,116,0
        ///Alabama State,14,117,1
        ///Alabama State,15,117,0
        ///Alabama State,16,117,2
        ///Alabama State,17,117,3
        ///Alcorn State,10,118,1
        ///Alcorn State,11,118,0
        ///Appalachian State,18,188,1
        ///Appalachian State,19,188,0
        ///Appalachian State,803,188,2
        ///Appalachian State,804,188,3
        ///Arizona,20,4,1
        ///Arizona,21,4,0
        ///Arizona,22,4,2
        ///Arizona,23,4,3
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TUNI_MASTER {
            get {
                return ResourceManager.GetString("TUNI_MASTER", resourceCulture);
            }
        }
    }
}
